"""
Django settings for skunkmonkey project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import shutil
from pathlib import Path

from django.urls import reverse

import dj_database_url
# Fix import to use environ instead of django_environ
from environ import Env  # noqa

# Initialize environment variables
env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Only load .env file if not on Heroku (determined by checking for DATABASE_URL)
if 'DATABASE_URL' not in os.environ:
    # Load environment variables from .env file
    env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)  # Get DEBUG from environment variable, default to False in production

# Determine if we're running on Heroku
ON_HEROKU = 'DATABASE_URL' in os.environ

ALLOWED_HOSTS = [
    'skunk.devel.hedge-monkey.co.uk',
    'localhost',
    '127.0.0.1',
    'hedgemonkey.ddns.net:8000',
    'hedgemonkey.ddns.net',
    'skunkmonkey.herokuapp.com',
    '.herokuapp.com',
    'devel.skunkmonkey.co.uk',
    'skunkmonkey.co.uk',
    'www.skunkmonkey.co.uk',
]

# Subdirectory configuration - only use FORCE_SCRIPT_NAME if not on Heroku
if not 'ON_HEROKU' in os.environ:
    FORCE_SCRIPT_NAME = '/dev'  # Updated from /devel to /dev
else:
    FORCE_SCRIPT_NAME = None  # Don't force script name on Heroku

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add sites framework required by allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'crispy_bootstrap5',
    'home',
    'users.apps.UsersConfig',
    'products',
    'shop',
    'staff.apps.StaffConfig',
    'djstripe',
    'django_countries',
    # Only include django_vite if not on Heroku
    'skunkmonkey',  # Add this to enable our custom templatetags
]

# Only include django_vite in INSTALLED_APPS if not on Heroku
if not ON_HEROKU:
    INSTALLED_APPS.append('django_vite')
    
    # Django-Vite configuration - SIMPLIFIED AND FIXED
    DJANGO_VITE_ASSETS_PATH = BASE_DIR / 'staticfiles'
    DJANGO_VITE_DEV_MODE = False
    DJANGO_VITE_DEV_SERVER_URL = ""
    
    # Clean up previous attempts at configuration
    # DJANGO_VITE_MANIFEST_PATH = os.path.join(BASE_DIR, 'staticfiles', 'manifest.json')
    # DJANGO_VITE_STATIC_URL_PREFIX = "/dev/static/"
    
    # Create a symlink in the exact location django-vite expects
    manifest_source = os.path.join(BASE_DIR, 'staticfiles', 'manifest.json')
    dev_static_dir = os.path.join(BASE_DIR, 'dev', 'static')
    manifest_target = os.path.join(dev_static_dir, 'manifest.json')
    
    # Ensure the target directory exists
    os.makedirs(dev_static_dir, exist_ok=True)
    
    # Copy the manifest file to the exact path django-vite is looking for
    if os.path.exists(manifest_source):
        shutil.copy2(manifest_source, manifest_target)
    
    # Simplified configuration with clean entry points
    DJANGO_VITE_CONFIGS = {
        'default': {
            'entry_points': ['main'],
        },
    }
    
    # Use a single, simplified configuration 
    DJANGO_VITE = {
        'default': {
            'dev_mode': False,
            'static_url_prefix': '/dev/static/',
        }
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add Whitenoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'shop.middleware.ComparisonMiddleware',
    'shop.middleware.CartMiddleware',  # Add the shop cart middleware
    'staff.middleware.StaffProfileMiddleware',  # Add middleware to handle staffprofile
    'staff.debug_middleware.StaffAuthDebugMiddleware',  # Add staff auth debugging middleware
    'csp.middleware.CSPMiddleware',    # Add Content Security Policy middleware
    'skunkmonkey.middleware.SourceMapIgnoreMiddleware',  # Add custom middleware to handle source map requests
]

# Content Security Policy settings
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_BROWSER_XSS_FILTER = True
# Configure CSP settings
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://*.cloudfront.net")
CSP_IMG_SRC = ("'self'", "data:", "https://*.stripe.com", "https://source.unsplash.com", "https://*.cloudfront.net", "https://*.amazonaws.com")
CSP_FONT_SRC = ("'self'", "data:", "https://fonts.gstatic.com", "https://use.fontawesome.com", "blob:", "https://*.cloudfront.net")
CSP_CONNECT_SRC = ("'self'", "https://*.stripe.com", "http://hedgemonkey.ddns.net:5173", "https://*.amazonaws.com", "https://*.cloudfront.net")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://js.stripe.com", "http://hedgemonkey.ddns.net:5173", "https://*.cloudfront.net")
CSP_FRAME_SRC = ("'self'", "https://*.stripe.com")

# Crispy Forms settings
CSP_FRAME_ANCESTORS = ("'self'",)

ROOT_URLCONF = 'skunkmonkey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'shop.context_processors.wishlist_processor',
                'staff.context_processors.unread_notifications',  # Add staff context processor
            ],
        },
    },
]

# Configure crispy_forms template pack
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

# Crispy Forms
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG

# Additional crispy form settings to fix template variable issues
CRISPY_CLASS_CONVERTERS = {
    'textinput': "form-control",
    'urlinput': "form-control",
    'numberinput': "form-control",
    'emailinput': "form-control",
    'dateinput': "form-control",
    'textarea': "form-control",
    'passwordinput': "form-control",
    'fileinput': "form-control",
}

# Define this variable globally to fix the wrapper_class issue
CRISPY_WRAPPER_CLASS = "mb-3"

# Override the default template pack settings for Bootstrap 5
CRISPY_BOOTSTRAP5_SETTINGS = {
    'wrapper_class': 'mb-3',  # This is the key setting for field wrapper
    'field_class': '',
    'label_class': '',
    'form_group_wrapper_class': '',
    'help_text_inline': True,
    'error_text_inline': True,
    'include_media': True,
}

WSGI_APPLICATION = 'skunkmonkey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'])
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Add authentication backends.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Allauth Configuration
SITE_ID = 1
LOGIN_REDIRECT_URL = '/dev/'  # Updated from /devel/ to /dev/
LOGOUT_REDIRECT_URL = '/dev/'  # Updated from /devel/ to /dev/
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_LOGIN_METHODS = ['email', 'username']
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_NOTIFICATIONS = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_UNIQUE_USERNAME = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True


def ACCOUNT_ACTIVATION_URL():
    return reverse('account_confirm_email') + '?code='


# Custom adapter to handle if email not verified
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_REAUTHENTICATION_REQUIRED = True
ACCOUNT_FORMS = {
    'add_email': 'allauth.account.forms.AddEmailForm',
    'change_password': 'allauth.account.forms.ChangePasswordForm',
    'confirm_login_code': 'allauth.account.forms.ConfirmLoginCodeForm',
    'login': 'users.forms.CustomLoginForm',
    'request_login_code': 'allauth.account.forms.RequestLoginCodeForm',
    'reset_password': 'allauth.account.forms.ResetPasswordForm',
    'reset_password_from_key': 'allauth.account.forms.ResetPasswordKeyForm',
    'set_password': 'allauth.account.forms.SetPasswordForm',
    'signup': 'allauth.account.forms.SignupForm',
    'user_token': 'allauth.account.forms.UserTokenForm',
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
print(f"DEBUG: EMAIL_HOST in os.environ: {'EMAIL_HOST' in os.environ}")
if 'EMAIL_HOST' in os.environ:
    print(f"DEBUG: Setting up SMTP backend with host: {os.environ['EMAIL_HOST']}")
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['EMAIL_HOST']
    EMAIL_PORT = int(os.environ['EMAIL_PORT'])
    EMAIL_USE_TLS = os.environ['EMAIL_USE_TLS'].lower() == 'true'
    EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
    DEFAULT_FROM_EMAIL = os.environ['DEFAULT_FROM_EMAIL']
else:
    print("DEBUG: EMAIL_HOST not found in environment, using console backend")
    # Add additional console backend settings if needed

# Configure Django to log all email-related actions
if DEBUG:
    EMAIL_DEBUG = True

# Add site URL and name settings for email templates
SITE_URL = env('SITE_URL', default='http://hedgemonkey.ddns.net:8000')
SITE_NAME = env('SITE_NAME', default='SkunkMonkey')
CONTACT_EMAIL = env('CONTACT_EMAIL', default=DEFAULT_FROM_EMAIL)

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/dev/static/'  # Updated from /devel/static/ to /dev/static/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_LOCATION = 'static'  # Define static files location for S3

# Media files - local settings that will be overridden if AWS is configured
MEDIA_URL = '/dev/media/'  # Updated from /devel/media/ to /dev/media/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIAFILES_LOCATION = 'media'

# Add storages to installed apps
INSTALLED_APPS += [
    'storages',
]

# Define default storage backends - these will be used if USE_S3 is True
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Use Whitenoise for static files on Heroku, otherwise use default storage
if 'ON_HEROKU' in os.environ:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Use AWS settings if configured - force to True in production mode
if env.bool('USE_S3', default=not DEBUG) or os.environ.get('USE_S3') == 'True':
    # Import AWS settings
    from .aws import *

    # Add debug output to confirm AWS settings are loaded
    print(f"DEBUG: AWS S3 enabled - using bucket {AWS_STORAGE_BUCKET_NAME}")
    print(f"DEBUG: AWS Region: {AWS_S3_REGION_NAME}")
    print(f"DEBUG: AWS CloudFront: {AWS_S3_CUSTOM_DOMAIN}")

    # Override storage backends for S3
    DEFAULT_FILE_STORAGE = 'skunkmonkey.custom_storages.MediaStorage'
    STATICFILES_STORAGE = 'skunkmonkey.custom_storages.StaticStorage'

    # If CloudFront is configured, use it for media URLs
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIAFILES_LOCATION}/"
        print(f"DEBUG: Using CloudFront for media: {MEDIA_URL}")

    # Now print the storage class after it's defined
    print(f"DEBUG: Media Storage: {DEFAULT_FILE_STORAGE}")
    print(f"DEBUG: Static Storage: {STATICFILES_STORAGE}")

# if os.environ.get("SKUNKMONKEY_VPS_HOST", False):
#   STATIC_URL = 'http://devel.skunkmonkey.co.uk/static/'
#   MEDIA_URL = 'http://devel.skunkmonkey.co.uk/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe settings
STRIPE_LIVE_MODE = env.bool('STRIPE_LIVE_MODE', default=False)

# Define these for your application's use
STRIPE_CURRENCY = 'gbp'  # British Pound as default currency

# These are here only as a reference for your application
# dj-stripe will manage the actual API keys through the admin
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')

# Use a stable API version
STRIPE_API_VERSION = "2023-10-16"

# Enable dj-stripe webhooks - important for proper webhook handling
DJSTRIPE_WEBHOOK_VALIDATION = "verify_signature"

# Make sure these environment variables are set in your .env file:
# STRIPE_PUBLISHABLE_KEY=pk_test_your_key
# STRIPE_SECRET_KEY=sk_test_your_key
# STRIPE_WEBHOOK_SECRET=whsec_your_key

# Enhanced logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {name} {module} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'auth_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'auth_debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'error_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'staff': {
            'handlers': ['console', 'file', 'auth_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'auth': {
            'handlers': ['console', 'auth_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Make sure log directories exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
