# Generated by Django 5.1.6 on 2025-04-24 01:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing Question'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('other', 'Other')], default='general', max_length=20, verbose_name='Category')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Staff Notes')),
                ('response', models.TextField(blank=True, verbose_name='Response Message')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Response Date')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email'], name='users_conta_email_94d804_idx'), models.Index(fields=['status'], name='users_conta_status_5ce107_idx'), models.Index(fields=['priority'], name='users_conta_priorit_57687d_idx'), models.Index(fields=['category'], name='users_conta_categor_506154_idx'), models.Index(fields=['timestamp'], name='users_conta_timesta_2865e0_idx'), models.Index(fields=['is_read'], name='users_conta_is_read_4631fa_idx')],
            },
        ),
    ]
