# Generated by Django 5.1.6 on 2025-04-24 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Note Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.contactmessage', verbose_name='Contact Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Message Note',
                'verbose_name_plural': 'Message Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='users_messa_created_e98362_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Response Content')),
                ('response_type', models.CharField(choices=[('message', 'Staff Message'), ('user_reply', 'User Reply'), ('phone_call_user', 'Phone Call - User Message'), ('phone_call_internal', 'Phone Call - Internal Only')], default='message', max_length=20, verbose_name='Response Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_visible_to_user', models.BooleanField(default=True, help_text='Whether this response is visible to the user', verbose_name='Visible to User')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether an email notification was sent to the user', verbose_name='Email Sent')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.contactmessage', verbose_name='Contact Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_responses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Message Response',
                'verbose_name_plural': 'Message Responses',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='users_messa_created_5a6fea_idx'), models.Index(fields=['response_type'], name='users_messa_respons_2bcea4_idx')],
            },
        ),
    ]
