repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: migrations/

    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "django", "--line-length", "79"]
        exclude: migrations/

    -   id: autopep8
        name: autopep8
        entry: autopep8
        language: system
        types: [python]
        args: ["--in-place", "--max-line-length", "79", "--aggressive", "--aggressive"]
        exclude: migrations/
