# Generated by Django 5.1.6 on 2025-04-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='category',
            field=models.CharField(choices=[('order', 'Order'), ('system', 'System'), ('user', 'User'), ('product', 'Product'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
