# Generated by Django 5.1.6 on 2025-03-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_2_9a'),
        ('shop', '0002_comparisonlist_recentlyvieweditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address1',
            field=models.CharField(default='123 Your Address', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='123 Your Billing Address', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='UK', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(default='County', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_zipcode',
            field=models.CharField(default='AA1 12B', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address1',
            field=models.CharField(default='123 Your Address', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='Your City', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='UK', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default='County', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zipcode',
            field=models.CharField(default='AA1 12B', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order')),
            ],
        ),
    ]
