# Generated by Django 5.1.6 on 2025-03-27 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributetype_alter_category_options_and_more'),
        ('shop', '0004_remove_payment_order_remove_wishlist_products_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='billing name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='recentlyvieweditem',
            index=models.Index(fields=['user', 'product'], name='shop_recent_user_prod_idx'),
        ),
    ]
