# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_billing_name_order_payment_method_type_and_more'),
    ]

    operations = [
        # Add session_id field
        migrations.AddField(
            model_name='comparisonlist',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Make user field optional
        migrations.AlterField(
            model_name='comparisonlist',
            name='user',
            field=models.ForeignKey('auth.User', blank=True, null=True, on_delete=models.CASCADE, related_name='comparison_lists'),
        ),
    ]
